"""
AuraNet feature engineering pipeline.

Supports two input formats:
  - Synthetic (11 cols)  : data/raw_train.csv  (generated by data/generate_dataset.py)
  - Real NSL-KDD (43 cols): data/KDDTrain_20Percent_raw.txt  (no header)

Steps
-----
1. Load + normalise schema (add column headers for NSL-KDD raw files)
2. Binarise label  -> "Normal" | "Attack"
3. Derive network_intensity = (src_bytes + dst_bytes) / duration  (clip denom at 1e-6)
4. LabelEncode all categorical columns (protocol_type, [service, flag])
5. StandardScale all numerical columns
6. Save -> data/processed_train.csv
"""

import sys
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

MODELS_DIR = Path("models")

# ── NSL-KDD column schema ─────────────────────────────────────────────────────

NSL_KDD_COLS = [
    "duration", "protocol_type", "service", "flag",
    "src_bytes", "dst_bytes", "land", "wrong_fragment", "urgent", "hot",
    "num_failed_logins", "logged_in", "num_compromised", "root_shell",
    "su_attempted", "num_root", "num_file_creations", "num_shells",
    "num_access_files", "num_outbound_cmds", "is_host_login", "is_guest_login",
    "count", "srv_count", "serror_rate", "srv_serror_rate", "rerror_rate",
    "srv_rerror_rate", "same_srv_rate", "diff_srv_rate", "srv_diff_host_rate",
    "dst_host_count", "dst_host_srv_count", "dst_host_same_srv_rate",
    "dst_host_diff_srv_rate", "dst_host_same_src_port_rate",
    "dst_host_srv_diff_host_rate", "dst_host_serror_rate",
    "dst_host_srv_serror_rate", "dst_host_rerror_rate",
    "dst_host_srv_rerror_rate", "label", "difficulty",
]

CATEGORICAL_COLS = ["protocol_type", "service", "flag"]

RAW_NSL_PATH  = Path("data/KDDTrain_20Percent_raw.txt")
RAW_SYN_PATH  = Path("data/raw_train.csv")
OUT_PATH      = Path("data/processed_train.csv")


# ── loading ───────────────────────────────────────────────────────────────────

def load_raw(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path, header=None)
    if df.shape[1] == len(NSL_KDD_COLS):
        df.columns = NSL_KDD_COLS
        df = df.drop(columns=["difficulty"])          # metadata, not a feature
        print(f"  Detected: real NSL-KDD  ({df.shape[1]} cols after drop)")
    else:
        # Synthetic data already has a header — reload with it
        df = pd.read_csv(path)
        print(f"  Detected: synthetic data ({df.shape[1]} cols)")
    return df


def binarise_label(df: pd.DataFrame) -> pd.DataFrame:
    """Map any non-'normal' class to 'Attack', normalise capitalisation."""
    df["label"] = df["label"].str.strip().str.lower()
    df["label"] = df["label"].apply(lambda x: "Normal" if x == "normal" else "Attack")
    return df


# ── feature engineering ───────────────────────────────────────────────────────

def derive_network_intensity(df: pd.DataFrame) -> pd.DataFrame:
    """
    (src_bytes + dst_bytes) / duration.
    duration is clipped at 1e-6 so near-zero connections (common in DoS) still
    produce a large signal rather than an inf/nan.
    """
    safe_duration = df["duration"].clip(lower=1e-6)
    df["network_intensity"] = (df["src_bytes"] + df["dst_bytes"]) / safe_duration
    return df


def encode_categoricals(df: pd.DataFrame) -> tuple[pd.DataFrame, dict]:
    encoders: dict[str, LabelEncoder] = {}
    present = [c for c in CATEGORICAL_COLS if c in df.columns]
    for col in present:
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col].astype(str))
        encoders[col] = le
        print(f"  {col:<16} {len(le.classes_):>3} classes -> int")
    return df, encoders


def scale_numerical(df: pd.DataFrame) -> tuple[pd.DataFrame, StandardScaler, list[str]]:
    skip = {"label"} | set(CATEGORICAL_COLS)
    num_cols = [c for c in df.select_dtypes(include=[np.number]).columns if c not in skip]
    scaler = StandardScaler()
    df[num_cols] = scaler.fit_transform(df[num_cols])
    print(f"  Scaled {len(num_cols)} numerical features.")
    return df, scaler, num_cols


# ── pipeline ──────────────────────────────────────────────────────────────────

def run_pipeline(raw_path: Path | None = None, out_path: Path = OUT_PATH) -> pd.DataFrame:
    if raw_path is None:
        raw_path = RAW_NSL_PATH if RAW_NSL_PATH.exists() else RAW_SYN_PATH

    print(f"\n[1/6] Loading  {raw_path} ...")
    df = load_raw(raw_path)
    print(f"      Shape: {df.shape}")

    print("[2/6] Binarising label ...")
    df = binarise_label(df)
    vc = df["label"].value_counts()
    print(f"      Normal: {vc.get('Normal', 0):,}  |  Attack: {vc.get('Attack', 0):,}")

    print("[3/6] Deriving network_intensity ...")
    df = derive_network_intensity(df)
    ni = df["network_intensity"]
    print(f"      min={ni.min():.2f}  mean={ni.mean():.2f}  max={ni.max():.2f}")

    print("[4/6] Encoding categorical columns ...")
    df, encoders = encode_categoricals(df)

    print("[5/6] Standard-scaling numerical features ...")
    df, scaler, num_cols = scale_numerical(df)

    print(f"[6/6] Saving processed data -> {out_path} ...")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(out_path, index=False)
    print(f"      Saved {len(df):,} rows x {df.shape[1]} cols.")

    _persist_artifacts(scaler, encoders, num_cols, df)
    _print_summary(df)
    return df


def _persist_artifacts(
    scaler: StandardScaler,
    encoders: dict,
    num_cols: list[str],
    df: pd.DataFrame,
) -> None:
    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    feature_order = [c for c in df.columns if c != "label"]

    joblib.dump(scaler,   MODELS_DIR / "scaler.joblib")
    joblib.dump(encoders, MODELS_DIR / "label_encoders.joblib")
    joblib.dump(
        {"feature_order": feature_order, "num_cols": num_cols},
        MODELS_DIR / "feature_meta.joblib",
    )
    print(f"\n[SAVE] Preprocessing artifacts -> {MODELS_DIR}/")
    print(f"       scaler.joblib  |  label_encoders.joblib  |  feature_meta.joblib")


def _print_summary(df: pd.DataFrame) -> None:
    num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    print("-- Scaled feature stats (sample) ----------------------------")
    print(df[num_cols[:8]].describe().T[["mean", "std", "min", "max"]].to_string())
    print("-------------------------------------------------------------\n")


if __name__ == "__main__":
    path = Path(sys.argv[1]) if len(sys.argv) > 1 else None
    if path is None and not RAW_NSL_PATH.exists() and not RAW_SYN_PATH.exists():
        print("ERROR: no raw data found. Run data/generate_dataset.py or download NSL-KDD.")
        sys.exit(1)
    run_pipeline(path)
